### ISSUE TITLE
Addon is unlisted

### ISSUE THREAD

**Issue by royvanv** [octoper/statamic-blade-components#14]
### Description

This addon is not recognised as an addon from the market place in the Statamic CP.

I reckon it is a mismatch between the package name `octoper/statamic-blade-components` and the market place URL "https://statamic.com/addons/octoper/blade-components".

### Steps to reproduce

1. Install the package via Composer
2. Go to CP > Addons > Installed
3. See the addon listed under the heading "Unlisted addons"

### Additional information

* Statamic version: 3.3.11 Pro
* PHP version: 8.1.4
* Other addons: None

**Comment by royvanv** [comment]
ping @octoper

**Comment by royvanv** [comment]
@octoper This issue has been open for over a year now. Could you look into it, please?

**Comment by octoper** [comment]
This has been resolved.
